### ISSUE TITLE
I'm getting flood wait error!

### ISSUE THREAD

**Issue by ritz0007** [nuhmanpk/pyrogram-bot#2]
After few minutes of testing I'm getting flood wait error. I have added code lines to translate this error instead of crashing, it says:

`Flood wait error: Waiting for 2546 seconds.`

Please figure out what is the issue, I even tried to change the bot token which helped me but then same error after few mins of testing. There's something wrong!!

**Comment by nuhmanpk** [comment]
Thanks @ritz0007 , Will look into it

**Comment by ritz0007** [comment]
Additional Info: 
- This flood wait is bot specific.
- It is random between 1500s to 3000s
- I run a few highly interactive bots and never faced this error before specially in case of a pyro bot session

Suggested Solution: 
- The issue is in `main.py` while storing the pyro session in memory instead of storing it as a file, cz it will lead to create and authorize the session every time the bot boots up. Which is unusual for telegram, cz it counts as a fresh new login. Remove the line `in_memory=True,` to fix this error!

**Comment by nuhmanpk** [comment]
Thanks @ritz0007 .
